In [81]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

sns.set(style="whitegrid", palette="muted", font_scale=1.1)
%matplotlib inline

In [ ]:
hungarian_path = os.path.join(os.getcwd(), '..', 'Data', 'raw', 'hungarian.data')
hungarian_df = pd.read_csv(hungarian_path, header=None)
va_path = os.path.join(os.getcwd(), '..', 'Data', 'raw', 'long-beach-va.data')
va_df = pd.read_csv(va_path, header=None)
new_path = os.path.join(os.getcwd(), '..', 'Data', 'raw', 'new.data')
new_df = pd.read_csv(new_path, header=None)
switzerland_path = os.path.join(os.getcwd(), '..', 'Data', 'raw', 'switzerland.data')
switzerland_df = pd.read_csv(switzerland_path, header=None)
df = pd.concat([hungarian_df, switzerland_df, va_df], ignore_index=True)

                              0
0             1254 0 40 1 1 0 0
1       -9 2 140 0 289 -9 -9 -9
2          0 -9 -9 0 12 16 84 0
3           0 0 0 0 150 18 -9 7
4     172 86 200 110 140 86 0 0
...                         ...
2935     0 -9 13 12 -9 -9 -9 -9
2936     -9 -9 -9 -9 -9 -9 -9 8
2937      5 84 0 -9 -9 -9 -9 -9
2938         -9 -9 -9 1 1 1 1 1
2939           1 1 -9. -9. name

[2940 rows x 1 columns]

In [83]:
with open(hungarian_path) as f:
    lines = [line.strip() for line in f]

patients = []
current_values = []

for line in lines:
    parts = line.split()

    # skip empty lines
    if not parts:
        continue

    # check if this line signals end of a patient
    if "name" in parts:

        # add remaining numbers to current patient
        current_values.extend(parts)

        # save patient
        patients.append(current_values)

        # reset for next patient
        current_values = []

    else:
        # just add numbers
        current_values.extend(parts)

In [84]:
column_names = [
"id", "ccf", "age", "sex", "painloc", "painexer", "relrest", "pncaden", "cp",
"trestbps", "htn", "chol", "smoke", "cigs", "years", "fbs", "dm", "famhist", 
"restecg", "ekgmo", "ekgday", "ekgyr", "dig", "prop", "nitr", "pro", "diuretic",
"proto", "thaldur", "thaltime", "met", "thalach", "thalrest", "tpeakbps", 
"tpeakbpd", "dummy", "trestbpd", "exang", "xhypo", "oldpeak", "slope", "rldv5",
"rldv5e", "ca", "restckm", "exerckm", "restef", "restwm", "exeref", "exerwm",
"thal", "thalsev", "thalpul", "earlobe", "cmo", "cday", "cyr", "num", "lmt",
"ladprox", "laddist", "diag", "cxmain", "ramus", "om1", "om2", "rcaprox", 
"rcadist", "lvx1", "lvx2", "lvx3", "lvx4", "lvf", "cathef", "junk", "name"
]
hungarian_df = pd.DataFrame(patients, columns=column_names)
hungarian_df

,id,ccf,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,...,rcaprox,rcadist,lvx1,lvx2,lvx3,lvx4,lvf,cathef,junk,name
0,1254,0,40,1,1,0,0,-9,2,140,...,-9,-9,1,1,1,1,1,-9.,-9.,name
1,1255,0,49,0,1,0,0,-9,3,160,...,-9,-9,1,1,1,1,1,-9.,-9.,name
2,1256,0,37,1,1,0,0,-9,2,130,...,-9,-9,1,1,1,1,1,-9.,-9.,name
3,1257,0,48,0,1,1,1,-9,4,138,...,2,-9,1,1,1,1,1,-9.,-9.,name
4,1258,0,54,1,1,0,1,-9,3,150,...,1,-9,1,1,1,1,1,-9.,-9.,name
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,1053,0,48,0,0,0,0,-9,2,-9,...,-9,-9,1,1,1,1,1,-9.,-9.,name
290,1054,0,36,1,1,0,0,-9,2,120,...,-9,-9,1,1,1,1,1,-9.,-9.,name
291,5001,0,48,1,0,0,0,-9,3,110,...,-9,-9,1,1,1,1,1,-9.,-9.,name
292,5000,0,47,0,0,0,0,-9,2,140,...,-9,-9,1,1,1,1,1,-9.,-9.,name
293,5002,0,53,1,1,1,1,-9,4,130,...,1,1,1,1,1,1,1,-9.,-9.,name

In [85]:
irrelevant_cols = ["id", "ccf", "dummy", "lvx1", "lvx2", "lvx3", "lvx4", "lvf", "cathef", "junk", "name", "thalsev", "thalpul", "earlobe", "restckm", "exerckm"]
hungarian_df.drop(columns=irrelevant_cols, inplace=True)
hungarian_df

,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,htn,chol,...,lmt,ladprox,laddist,diag,cxmain,ramus,om1,om2,rcaprox,rcadist
0,40,1,1,0,0,-9,2,140,0,289,...,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9
1,49,0,1,0,0,-9,3,160,1,180,...,-9,-9,2,-9,-9,-9,-9,-9,-9,-9
2,37,1,1,0,0,-9,2,130,0,283,...,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9
3,48,0,1,1,1,-9,4,138,0,214,...,-9,2,-9,-9,2,-9,-9,-9,2,-9
4,54,1,1,0,1,-9,3,150,0,-9,...,-9,-9,-9,-9,1,-9,-9,-9,1,-9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,48,0,0,0,0,-9,2,-9,0,308,...,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9
290,36,1,1,0,0,-9,2,120,0,166,...,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9
291,48,1,0,0,0,-9,3,110,0,211,...,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9
292,47,0,0,0,0,-9,2,140,1,257,...,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9
293,53,1,1,1,1,-9,4,130,0,182,...,-9,-9,-9,-9,-9,-9,-9,-9,1,1