In [205]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

sns.set(style="whitegrid", palette="muted", font_scale=1.1)
%matplotlib inline

In [206]:
hungarian_path = os.path.join(os.getcwd(), '..', 'Data', 'raw', 'hungarian.data')
hungarian_df = pd.read_csv(hungarian_path, header=None)
va_path = os.path.join(os.getcwd(), '..', 'Data', 'raw', 'long-beach-va.data')
va_df = pd.read_csv(va_path, header=None)
switzerland_path = os.path.join(os.getcwd(), '..', 'Data', 'raw', 'switzerland.data')
switzerland_df = pd.read_csv(switzerland_path, header=None)
df = pd.concat([hungarian_df, switzerland_df, va_df], ignore_index=True)

In [207]:
def get_patients(path):
    patients = []

    with open(path) as f:
        lines = [line.strip() for line in f]

    current_values = []

    for line in lines:
        parts = line.split()

        if not parts:
            continue

        if "name" in parts:

            current_values.extend(parts)

            patients.append(current_values)

            current_values = []

        else:
            current_values.extend(parts)
    return patients

   -- Complete attribute documentation:
      1 id: patient identification number
      2 ccf: social security number (I replaced this with a dummy value of 0)
      3 age: age in years
      4 sex: sex (1 = male; 0 = female)
      5 painloc: chest pain location (1 = substernal; 0 = otherwise)
      6 painexer (1 = provoked by exertion; 0 = otherwise)
      7 relrest (1 = relieved after rest; 0 = otherwise)
      8 pncaden (sum of 5, 6, and 7)
      9 cp: chest pain type
        -- Value 1: typical angina
        -- Value 2: atypical angina
        -- Value 3: non-anginal pain
        -- Value 4: asymptomatic
     10 trestbps: resting blood pressure (in mm Hg on admission to the 
        hospital)
     11 htn
     12 chol: serum cholestoral in mg/dl
     13 smoke: I believe this is 1 = yes; 0 = no (is or is not a smoker)
     14 cigs (cigarettes per day)
     15 years (number of years as a smoker)
     16 fbs: (fasting blood sugar > 120 mg/dl)  (1 = true; 0 = false)
     17 dm (1 = history of diabetes; 0 = no such history)
     18 famhist: family history of coronary artery disease (1 = yes; 0 = no)
     19 restecg: resting electrocardiographic results
        -- Value 0: normal
        -- Value 1: having ST-T wave abnormality (T wave inversions and/or ST 
                    elevation or depression of > 0.05 mV)
        -- Value 2: showing probable or definite left ventricular hypertrophy
                    by Estes' criteria
     20 ekgmo (month of exercise ECG reading)
     21 ekgday(day of exercise ECG reading)
     22 ekgyr (year of exercise ECG reading)
     23 dig (digitalis used furing exercise ECG: 1 = yes; 0 = no)
     24 prop (Beta blocker used during exercise ECG: 1 = yes; 0 = no)
     25 nitr (nitrates used during exercise ECG: 1 = yes; 0 = no)
     26 pro (calcium channel blocker used during exercise ECG: 1 = yes; 0 = no)
     27 diuretic (diuretic used used during exercise ECG: 1 = yes; 0 = no)
     28 proto: exercise protocol
          1 = Bruce     
          2 = Kottus
          3 = McHenry
          4 = fast Balke
          5 = Balke
          6 = Noughton 
          7 = bike 150 kpa min/min  (Not sure if "kpa min/min" is what was 
              written!)
          8 = bike 125 kpa min/min  
          9 = bike 100 kpa min/min
         10 = bike 75 kpa min/min
         11 = bike 50 kpa min/min
         12 = arm ergometer
     29 thaldur: duration of exercise test in minutes
     30 thaltime: time when ST measure depression was noted
     31 met: mets achieved
     32 thalach: maximum heart rate achieved
     33 thalrest: resting heart rate
     34 tpeakbps: peak exercise blood pressure (first of 2 parts)
     35 tpeakbpd: peak exercise blood pressure (second of 2 parts)
     36 dummy
     37 trestbpd: resting blood pressure
     38 exang: exercise induced angina (1 = yes; 0 = no)
     39 xhypo: (1 = yes; 0 = no)
     40 oldpeak = ST depression induced by exercise relative to rest
     41 slope: the slope of the peak exercise ST segment
        -- Value 1: upsloping
        -- Value 2: flat
        -- Value 3: downsloping
     42 rldv5: height at rest
     43 rldv5e: height at peak exercise
     44 ca: number of major vessels (0-3) colored by flourosopy
     45 restckm: irrelevant
     46 exerckm: irrelevant
     47 restef: rest raidonuclid (sp?) ejection fraction
     48 restwm: rest wall (sp?) motion abnormality
        0 = none
        1 = mild or moderate
        2 = moderate or severe
        3 = akinesis or dyskmem (sp?)
     49 exeref: exercise radinalid (sp?) ejection fraction
     50 exerwm: exercise wall (sp?) motion 
     51 thal: 3 = normal; 6 = fixed defect; 7 = reversable defect
     52 thalsev: not used
     53 thalpul: not used
     54 earlobe: not used
     55 cmo: month of cardiac cath (sp?)  (perhaps "call")
     56 cday: day of cardiac cath (sp?)
     57 cyr: year of cardiac cath (sp?)
     58 num: diagnosis of heart disease (angiographic disease status)
        -- Value 0: < 50% diameter narrowing
        -- Value 1: > 50% diameter narrowing
        (in any major vessel: attributes 59 through 68 are vessels)
     59 lmt
     60 ladprox
     61 laddist
     62 diag
     63 cxmain
     64 ramus
     65 om1
     66 om2
     67 rcaprox
     68 rcadist
     69 lvx1: not used
     70 lvx2: not used
     71 lvx3: not used
     72 lvx4: not used
     73 lvf: not used
     74 cathef: not used
     75 junk: not used
     76 name: last name of patient

#### Column 58: num is the target which indicates if the patients have a heart disease

In [ ]:
column_names = [
"id", "ccf", "age", "sex", "painloc", "painexer", "relrest", "pncaden", "cp",
"trestbps", "htn", "chol", "smoke", "cigs", "years", "fbs", "dm", "famhist", 
"restecg", "ekgmo", "ekgday", "ekgyr", "dig", "prop", "nitr", "pro", "diuretic",
"proto", "thaldur", "thaltime", "met", "thalach", "thalrest", "tpeakbps", 
"tpeakbpd", "dummy", "trestbpd", "exang", "xhypo", "oldpeak", "slope", "rldv5",
"rldv5e", "ca", "restckm", "exerckm", "restef", "restwm", "exeref", "exerwm",
"thal", "thalsev", "thalpul", "earlobe", "cmo", "cday", "cyr", "num", "lmt",
"ladprox", "laddist", "diag", "cxmain", "ramus", "om1", "om2", "rcaprox", 
"rcadist", "lvx1", "lvx2", "lvx3", "lvx4", "lvf", "cathef", "junk", "name"
]



hungarian_patients = get_patients(hungarian_path)
va_patients = get_patients(va_path)
switzerland_patients = get_patients(switzerland_path)

In [209]:

hungarian_df = pd.DataFrame(hungarian_patients, columns=column_names)
hungarian_df

,id,ccf,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,...,rcaprox,rcadist,lvx1,lvx2,lvx3,lvx4,lvf,cathef,junk,name
0,1254,0,40,1,1,0,0,-9,2,140,...,-9,-9,1,1,1,1,1,-9.,-9.,name
1,1255,0,49,0,1,0,0,-9,3,160,...,-9,-9,1,1,1,1,1,-9.,-9.,name
2,1256,0,37,1,1,0,0,-9,2,130,...,-9,-9,1,1,1,1,1,-9.,-9.,name
3,1257,0,48,0,1,1,1,-9,4,138,...,2,-9,1,1,1,1,1,-9.,-9.,name
4,1258,0,54,1,1,0,1,-9,3,150,...,1,-9,1,1,1,1,1,-9.,-9.,name
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,1053,0,48,0,0,0,0,-9,2,-9,...,-9,-9,1,1,1,1,1,-9.,-9.,name
290,1054,0,36,1,1,0,0,-9,2,120,...,-9,-9,1,1,1,1,1,-9.,-9.,name
291,5001,0,48,1,0,0,0,-9,3,110,...,-9,-9,1,1,1,1,1,-9.,-9.,name
292,5000,0,47,0,0,0,0,-9,2,140,...,-9,-9,1,1,1,1,1,-9.,-9.,name
293,5002,0,53,1,1,1,1,-9,4,130,...,1,1,1,1,1,1,1,-9.,-9.,name

In [210]:
va_df = pd.DataFrame(va_patients, columns=column_names)
va_df

,id,ccf,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,...,rcaprox,rcadist,lvx1,lvx2,lvx3,lvx4,lvf,cathef,junk,name
0,1,0,63,1,1,1,1,-9,4,140,...,2,1,1,1,1,1,1,0.7,5.5,name
1,2,0,44,1,1,1,1,-9,4,130,...,1,1,1,1,1,1,1,0.5,-9.,name
2,3,0,60,1,1,1,1,-9,4,132,...,2,1,1,1,1,7,2,0.52,4.1,name
3,4,0,55,1,1,1,1,-9,4,142,...,1,1,1,1,1,1,1,0.73,6.5,name
4,5,0,66,1,1,0,0,-9,3,110,...,1,1,1,1,1,1,1,0.73,8,name
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,200,0,54,0,1,1,1,-9,4,127,...,1,1,1,1,1,1,1,0.76,5.6,name
196,201,0,62,1,0,0,0,-9,1,-9,...,1,1,1,1,1,1,2,0.62,3.5,name
197,202,0,55,1,1,1,1,-9,4,122,...,2,1,1,1,1,1,1,0.69,5.6,name
198,116,0,58,1,1,1,1,-9,4,-9,...,1,1,1,1,1,1,1,0.81,6,name
199,160,0,62,1,1,0,0,-9,2,120,...,2,1,1,1,1,1,1,-9,-9.,name

In [211]:
switzerland_df = pd.DataFrame(switzerland_patients, columns=column_names)
switzerland_df

,id,ccf,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,...,rcaprox,rcadist,lvx1,lvx2,lvx3,lvx4,lvf,cathef,junk,name
0,3001,0,65,1,1,1,1,-9,4,115,...,1,1,1,1,1,1,1,75,-9.,name
1,3002,0,32,1,0,0,0,-9,1,95,...,1,1,1,1,1,5,1,63,-9.,name
2,3003,0,61,1,1,1,1,-9,4,105,...,2,1,1,1,1,1,1,67,-9.,name
3,3004,0,50,1,1,1,1,-9,4,145,...,1,1,1,1,1,5,4,36,-9.,name
4,3005,0,57,1,1,1,1,-9,4,110,...,2,1,1,1,1,1,1,60,-9.,name
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,4070,0,54,1,1,1,1,-9,4,180,...,1,1,1,1,1,1,1,71,-9.,name
119,4071,0,56,1,1,1,1,-9,4,125,...,2,1,5,1,1,1,2,68,-9.,name
120,4072,0,56,1,0,1,1,-9,3,125,...,1,1,1,1,5,3,2,61,-9.,name
121,4073,0,54,1,1,1,1,-9,4,130,...,2,1,1,1,1,1,1,-9.,-9.,name
122,4074,0,66,0,1,1,1,-9,4,155,...,2,1,1,1,1,1,1,70,-9.,name

In [212]:
df = pd.concat([hungarian_df, va_df, switzerland_df])
df

,id,ccf,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,...,rcaprox,rcadist,lvx1,lvx2,lvx3,lvx4,lvf,cathef,junk,name
0,1254,0,40,1,1,0,0,-9,2,140,...,-9,-9,1,1,1,1,1,-9.,-9.,name
1,1255,0,49,0,1,0,0,-9,3,160,...,-9,-9,1,1,1,1,1,-9.,-9.,name
2,1256,0,37,1,1,0,0,-9,2,130,...,-9,-9,1,1,1,1,1,-9.,-9.,name
3,1257,0,48,0,1,1,1,-9,4,138,...,2,-9,1,1,1,1,1,-9.,-9.,name
4,1258,0,54,1,1,0,1,-9,3,150,...,1,-9,1,1,1,1,1,-9.,-9.,name
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,4070,0,54,1,1,1,1,-9,4,180,...,1,1,1,1,1,1,1,71,-9.,name
119,4071,0,56,1,1,1,1,-9,4,125,...,2,1,5,1,1,1,2,68,-9.,name
120,4072,0,56,1,0,1,1,-9,3,125,...,1,1,1,1,5,3,2,61,-9.,name
121,4073,0,54,1,1,1,1,-9,4,130,...,2,1,1,1,1,1,1,-9.,-9.,name
122,4074,0,66,0,1,1,1,-9,4,155,...,2,1,1,1,1,1,1,70,-9.,name

# Step 2: Data Cleaning Workflow
## 1/ Inspect the Data Structure

In [213]:
df.shape
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 617 entries, 0 to 122
Data columns (total 76 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        617 non-null    object
 1   ccf       617 non-null    object
 2   age       617 non-null    object
 3   sex       617 non-null    object
 4   painloc   617 non-null    object
 5   painexer  617 non-null    object
 6   relrest   617 non-null    object
 7   pncaden   617 non-null    object
 8   cp        617 non-null    object
 9   trestbps  617 non-null    object
 10  htn       617 non-null    object
 11  chol      617 non-null    object
 12  smoke     617 non-null    object
 13  cigs      617 non-null    object
 14  years     617 non-null    object
 15  fbs       617 non-null    object
 16  dm        617 non-null    object
 17  famhist   617 non-null    object
 18  restecg   617 non-null    object
 19  ekgmo     617 non-null    object
 20  ekgday    617 non-null    object
 21  ekgyr     617 non-null    object
 22  dig       617 non-null    object
 23  prop      617 non-null    object
 24  nitr      617 non-null    object
 25  pro       617 non-null    object
 26  diuretic  617 non-null    object
 27  proto     617 non-null    object
 28  thaldur   617 non-null    object
 29  thaltime  617 non-null    object
 30  met       617 non-null    object
 31  thalach   617 non-null    object
 32  thalrest  617 non-null    object
 33  tpeakbps  617 non-null    object
 34  tpeakbpd  617 non-null    object
 35  dummy     617 non-null    object
 36  trestbpd  617 non-null    object
 37  exang     617 non-null    object
 38  xhypo     617 non-null    object
 39  oldpeak   617 non-null    object
 40  slope     617 non-null    object
 41  rldv5     617 non-null    object
 42  rldv5e    617 non-null    object
 43  ca        617 non-null    object
 44  restckm   617 non-null    object
 45  exerckm   617 non-null    object
 46  restef    617 non-null    object
 47  restwm    617 non-null    object
 48  exeref    617 non-null    object
 49  exerwm    617 non-null    object
 50  thal      617 non-null    object
 51  thalsev   617 non-null    object
 52  thalpul   617 non-null    object
 53  earlobe   617 non-null    object
 54  cmo       617 non-null    object
 55  cday      617 non-null    object
 56  cyr       617 non-null    object
 57  num       617 non-null    object
 58  lmt       617 non-null    object
 59  ladprox   617 non-null    object
 60  laddist   617 non-null    object
 61  diag      617 non-null    object
 62  cxmain    617 non-null    object
 63  ramus     617 non-null    object
 64  om1       617 non-null    object
 65  om2       617 non-null    object
 66  rcaprox   617 non-null    object
 67  rcadist   617 non-null    object
 68  lvx1      617 non-null    object
 69  lvx2      617 non-null    object
 70  lvx3      617 non-null    object
 71  lvx4      617 non-null    object
 72  lvf       617 non-null    object
 73  cathef    617 non-null    object
 74  junk      617 non-null    object
 75  name      617 non-null    object
dtypes: object(76)
memory usage: 371.2+ KB

## 2/ Standardize Missing Values

In [214]:
import numpy as np

df.replace("?", np.nan, inplace=True)
df.replace("NA", np.nan, inplace=True)
df.replace("-9", np.nan, inplace=True)

df.isna().sum()

C:\Users\hcant\AppData\Local\Temp\ipykernel_20780\3604265297.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("-9", np.nan, inplace=True)

id          0
ccf         0
age         0
sex         0
painloc     0
           ..
lvx4       19
lvf        16
cathef     24
junk        1
name        0
Length: 76, dtype: int64

## 3/ Convert Data Types

In [215]:
df = df.apply(pd.to_numeric, errors="ignore")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 617 entries, 0 to 122
Data columns (total 76 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        617 non-null    int64
 1   ccf       617 non-null    int64
 2   age       617 non-null    int64
 3   sex       617 non-null    int64
 4   painloc   617 non-null    int64
 5   painexer  617 non-null    int64
 6   relrest   613 non-null    float64
 7   pncaden   0 non-null      float64
 8   cp        617 non-null    int64
 9   trestbps  558 non-null    float64
 10  htn       583 non-null    float64
 11  chol      587 non-null    float64
 12  smoke     230 non-null    float64
 13  cigs      202 non-null    float64
 14  years     190 non-null    float64
 15  fbs       527 non-null    float64
 16  dm        72 non-null     float64
 17  famhist   195 non-null    float64
 18  restecg   615 non-null    float64
 19  ekgmo     564 non-null    float64
 20  ekgday    563 non-null    float64
 21  ekgyr     564 non-null    float64
 22  dig       551 non-null    float64
 23  prop      553 non-null    float64
 24  nitr      554 non-null    float64
 25  pro       556 non-null    float64
 26  diuretic  537 non-null    float64
 27  proto     505 non-null    float64
 28  thaldur   561 non-null    float64
 29  thaltime  233 non-null    float64
 30  met       512 non-null    float64
 31  thalach   562 non-null    float64
 32  thalrest  561 non-null    float64
 33  tpeakbps  554 non-null    float64
 34  tpeakbpd  554 non-null    float64
 35  dummy     558 non-null    float64
 36  trestbpd  558 non-null    float64
 37  exang     562 non-null    float64
 38  xhypo     559 non-null    float64
 39  oldpeak   555 non-null    float64
 40  slope     309 non-null    float64
 41  rldv5     474 non-null    float64
 42  rldv5e    475 non-null    float64
 43  ca        11 non-null     float64
 44  restckm   0 non-null      float64
 45  exerckm   1 non-null      float64
 46  restef    28 non-null     float64
 47  restwm    30 non-null     float64
 48  exeref    2 non-null      float64
 49  exerwm    5 non-null      float64
 50  thal      142 non-null    float64
 51  thalsev   130 non-null    float64
 52  thalpul   44 non-null     float64
 53  earlobe   1 non-null      float64
 54  cmo       606 non-null    float64
 55  cday      608 non-null    float64
 56  cyr       608 non-null    float64
 57  num       617 non-null    int64
 58  lmt       342 non-null    float64
 59  ladprox   381 non-null    float64
 60  laddist   371 non-null    float64
 61  diag      341 non-null    float64
 62  cxmain    382 non-null    float64
 63  ramus     332 non-null    float64
 64  om1       346 non-null    float64
 65  om2       327 non-null    float64
 66  rcaprox   372 non-null    float64
 67  rcadist   347 non-null    float64
 68  lvx1      598 non-null    float64
 69  lvx2      598 non-null    float64
 70  lvx3      598 non-null    float64
 71  lvx4      598 non-null    float64
 72  lvf       601 non-null    float64
 73  cathef    593 non-null    float64
 74  junk      616 non-null    float64
 75  name      617 non-null    object
dtypes: float64(67), int64(8), object(1)
memory usage: 371.2+ KB

C:\Users\hcant\AppData\Local\Temp\ipykernel_20780\2304015745.py:1: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors="ignore")

## 4/ Remove Irrelevant Columns

### Each feature was assessed for relevance, and variables that did not provide meaningful information for identifying heart disease were discarded.

### These features were not considered, as they do not provide meaningful information in the context of the original dataset.

#### restckm, exerckm, thalsev, thalpul, earlobe, lvx1, lvx2, lvx3, lvx4, lvf, cathef, junk, dummy, id, ccf, name

### These variables were excluded from the analysis. Although they may carry some significance, they should not be used as primary determinants since additional factors such as genetics and other underlying conditions must also be considered.

#### smoke, cigs, years, dm, famhist

### Certain clinically relevant features were considered but ultimately omitted from the model to avoid multicollinearity, overfitting, and other issues associated with high-dimensional datasets.

#### pncaden, ekgmo, ekgday, ekgyr, dig, prop, nitr, pro, diuretic, proto, thaltime, trestbpd, rldv5, rldv5e, cmo, cday, cyr, painloc, painexer, relrest, trestbps, htn, thaldur, met, thalach, tpeakbps, tpeakbpd, xhypo, restef, restwm, exeref, exerwm, lmt, ladprox, laddist, diag, cxmain, ramus, om1, om2, rcaprox, and rcadist.

#### The selected 13 features: age, sex, cp (chest pain type), trestbps (resting blood pressure), chol (serum cholesterol), fbs (fasting blood sugar), restecg (resting ECG results), thalach (maximum heart rate achieved), exang (exercise-induced angina), oldpeak (ST depression), slope (ST segment slope), ca (number of major vessels colored by fluoroscopy), and thal (thalassemia status), were retained due to their well-established clinical relevance in predicting coronary artery disease. These features capture demographic information, cardiovascular risk factors, symptom presentation, exercise response, and imaging-based cardiac assessments, and have been validated across multiple studies as significant predictors of heart disease. Their inclusion aligns with standard practice in cardiovascular research and ensures that the model is both interpretable and grounded in clinical evidence. Of course without forgetting the predicted attribute.

In [228]:
relevant_columns = [
    "age", "sex", "cp", "trestbps", "chol", "fbs", "restecg", "thalach",
    "exang", "oldpeak", "slope", "ca", "thal", "num"
]

df= df[relevant_columns]
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,40,1,2,140.0,289.0,0.0,0.0,172.0,0.0,0.0,NaN,NaN,NaN,0
1,49,0,3,160.0,180.0,0.0,0.0,156.0,0.0,1.0,2.0,NaN,NaN,1
2,37,1,2,130.0,283.0,0.0,1.0,98.0,0.0,0.0,NaN,NaN,NaN,0
3,48,0,4,138.0,214.0,0.0,0.0,108.0,1.0,1.5,2.0,NaN,NaN,3
4,54,1,3,150.0,NaN,0.0,0.0,122.0,0.0,0.0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118,54,1,4,180.0,0.0,NaN,0.0,150.0,0.0,1.5,2.0,NaN,7.0,1
119,56,1,4,125.0,0.0,1.0,0.0,103.0,1.0,1.0,2.0,NaN,7.0,3
120,56,1,3,125.0,0.0,NaN,0.0,98.0,0.0,-2.0,2.0,NaN,7.0,2
121,54,1,4,130.0,0.0,NaN,0.0,110.0,1.0,3.0,2.0,NaN,7.0,3
122,66,0,4,155.0,0.0,NaN,0.0,90.0,0.0,0.0,NaN,NaN,7.0,1

## 5/Handle Missing Data

In [230]:
missing_percent = df.isna().mean() * 100

print(missing_percent.sort_values(ascending=False))

cols_to_drop = missing_percent[missing_percent > 30].index
df = df.drop(columns=cols_to_drop)

numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

categorical_cols = df.select_dtypes(include=["object", "category"]).columns
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

age         0.0
sex         0.0
cp          0.0
trestbps    0.0
chol        0.0
fbs         0.0
restecg     0.0
thalach     0.0
exang       0.0
oldpeak     0.0
num         0.0
dtype: float64

## 6/Remove Duplicate Rows

In [218]:
df = df.drop_duplicates()

## 7/ Validate Value Ranges

In [219]:
df.describe()

,age,sex,painloc,painexer,relrest,pncaden,cp,trestbps,htn,chol,...,lmt,ladprox,laddist,diag,cxmain,ramus,om1,om2,rcaprox,rcadist
count,617.000000,617.000000,617.000000,617.000000,613.000000,0.0,617.000000,558.000000,583.000000,587.000000,...,342.000000,381.000000,371.000000,341.000000,382.000000,332.000000,346.000000,327.000000,372.000000,347.000000
mean,53.055105,0.842788,0.920583,0.593193,0.672104,NaN,3.294976,132.372760,0.408233,174.579216,...,1.555556,1.464567,1.280323,1.202346,1.400524,1.114458,1.187861,1.067278,1.470430,1.207493
std,9.582869,0.364296,0.270607,0.491637,0.469830,NaN,0.913743,19.828097,0.491929,124.349962,...,8.706091,0.499399,0.449764,0.402339,0.490647,0.318847,0.391167,0.250887,0.499797,0.406097
min,28.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.000000,0.000000,0.000000,0.000000,...,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,47.000000,1.000000,1.000000,0.000000,0.000000,NaN,3.000000,120.000000,0.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,54.000000,1.000000,1.000000,1.000000,1.000000,NaN,4.000000,130.000000,0.000000,214.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,60.000000,1.000000,1.000000,1.000000,1.000000,NaN,4.000000,142.000000,1.000000,263.000000,...,1.000000,2.000000,2.000000,1.000000,2.000000,1.000000,1.000000,1.000000,2.000000,1.000000
max,77.000000,1.000000,1.000000,1.000000,1.000000,NaN,4.000000,200.000000,1.000000,603.000000,...,162.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

In [221]:
## 8/ Check Categorical Variables
## 10/ Verify Final Dataset

In [226]:
categorical_cols = [col for col in df.columns if df[col].nunique() <= 10]
print("len: ", len(categorical_cols))
print(categorical_cols)

len:  38
['sex', 'painloc', 'painexer', 'relrest', 'pncaden', 'cp', 'htn', 'smoke', 'fbs', 'dm', 'famhist', 'restecg', 'ekgyr', 'dig', 'prop', 'nitr', 'pro', 'diuretic', 'exang', 'xhypo', 'slope', 'ca', 'restwm', 'exeref', 'exerwm', 'thal', 'cyr', 'num', 'lmt', 'ladprox', 'laddist', 'diag', 'cxmain', 'ramus', 'om1', 'om2', 'rcaprox', 'rcadist']

In [227]:
for col in categorical_cols:
    print(f"\nColumn: {col}")
    print("Unique values:", df[col].unique())
    print("Counts:")
    print(df[col].value_counts())

Column: sex
Unique values: [1 0]
Counts:
sex
1    520
0     97
Name: count, dtype: int64

Column: painloc
Unique values: [1 0]
Counts:
painloc
1    568
0     49
Name: count, dtype: int64

Column: painexer
Unique values: [0 1]
Counts:
painexer
1    366
0    251
Name: count, dtype: int64

Column: relrest
Unique values: [ 0.  1. nan]
Counts:
relrest
1.0    412
0.0    201
Name: count, dtype: int64

Column: pncaden
Unique values: [nan]
Counts:
Series([], Name: count, dtype: int64)

Column: cp
Unique values: [2 3 4 1]
Counts:
cp
4    352
2    124
3    118
1     23
Name: count, dtype: int64

Column: htn
Unique values: [ 0.  1. nan]
Counts:
htn
0.0    345
1.0    238
Name: count, dtype: int64

Column: smoke
Unique values: [nan  0.  1.]
Counts:
smoke
1.0    119
0.0    111
Name: count, dtype: int64

Column: fbs
Unique values: [ 0. nan  1.]
Counts:
fbs
0.0    434
1.0     93
Name: count, dtype: int64

Column: dm
Unique values: [nan  1.  0.]
Counts:
dm
1.0    68
0.0     4
Name: count, dtype: int64

Column: famhist
Unique values: [nan  0.  1.]
Counts:
famhist
0.0    101
1.0     94
Name: count, dtype: int64

Column: restecg
Unique values: [ 0.  1.  2. nan]
Counts:
restecg
0.0    400
1.0    175
2.0     40
Name: count, dtype: int64

Column: ekgyr
Unique values: [84. 85. 87. 83. 86. nan 82. 81.]
Counts:
ekgyr
85.0    183
86.0    143
84.0    138
83.0     54
87.0     41
82.0      4
81.0      1
Name: count, dtype: int64

Column: dig
Unique values: [ 0. nan  1.]
Counts:
dig
0.0    531
1.0     20
Name: count, dtype: int64

Column: prop
Unique values: [ 0.  1. nan 22.]
Counts:
prop
0.0     432
1.0     120
22.0      1
Name: count, dtype: int64

Column: nitr
Unique values: [ 0.  1. nan]
Counts:
nitr
0.0    401
1.0    153
Name: count, dtype: int64

Column: pro
Unique values: [ 0.  1. nan]
Counts:
pro
0.0    440
1.0    116
Name: count, dtype: int64

Column: diuretic
Unique values: [ 0. nan  1.]
Counts:
diuretic
0.0    477
1.0     60
Name: count, dtype: int64

Column: exang
Unique values: [ 0.  1. nan]
Counts:
exang
0.0    324
1.0    238
Name: count, dtype: int64

Column: xhypo
Unique values: [ 0.  1. nan]
Counts:
xhypo
0.0    543
1.0     16
Name: count, dtype: int64

Column: slope
Unique values: [nan  2.  1.  3.  0.]
Counts:
slope
2.0    205
1.0     61
3.0     42
0.0      1
Name: count, dtype: int64

Column: ca
Unique values: [nan  9.  0.  1.  2.]
Counts:
ca
0.0    5
2.0    3
1.0    2
9.0    1
Name: count, dtype: int64

Column: restwm
Unique values: [nan  0.  1.  2.  3.]
Counts:
restwm
0.0    13
2.0     8
1.0     6
3.0     3
Name: count, dtype: int64

Column: exeref
Unique values: [nan 0.6 0.5]
Counts:
exeref
0.6    1
0.5    1
Name: count, dtype: int64

Column: exerwm
Unique values: [nan  0.  1.]
Counts:
exerwm
0.0    4
1.0    1
Name: count, dtype: int64

Column: thal
Unique values: [nan  7.  3.  6.  2.  5.  1.  4.]
Counts:
thal
7.0    75
3.0    30
6.0    28
1.0     4
5.0     3
2.0     1
4.0     1
Name: count, dtype: int64

Column: cyr
Unique values: [84. 85. 87. 83. 86. 82. 80.  1. 26. 16. nan]
Counts:
cyr
85.0    179
86.0    158
84.0    137
83.0     78
87.0     47
82.0      5
80.0      1
1.0       1
26.0      1
16.0      1
Name: count, dtype: int64

Column: num
Unique values: [0 1 3 4 2]
Counts:
num
0    247
1    141
3    100
2     99
4     30
Name: count, dtype: int64

Column: lmt
Unique values: [ nan   2.   1. 162.   0.]
Counts:
lmt
1.0      310
2.0       30
162.0      1
0.0        1
Name: count, dtype: int64

Column: ladprox
Unique values: [nan  2.  1.]
Counts:
ladprox
1.0    204
2.0    177
Name: count, dtype: int64

Column: laddist
Unique values: [nan  2.  1.]
Counts:
laddist
1.0    267
2.0    104
Name: count, dtype: int64

Column: diag
Unique values: [nan  2.  1.]
Counts:
diag
1.0    272
2.0     69
Name: count, dtype: int64

Column: cxmain
Unique values: [nan  2.  1.]
Counts:
cxmain
1.0    229
2.0    153
Name: count, dtype: int64

Column: ramus
Unique values: [nan  2.  1.]
Counts:
ramus
1.0    294
2.0     38
Name: count, dtype: int64

Column: om1
Unique values: [nan  2.  1.]
Counts:
om1
1.0    281
2.0     65
Name: count, dtype: int64

Column: om2
Unique values: [nan  2.  1.]
Counts:
om2
1.0    305
2.0     22
Name: count, dtype: int64

Column: rcaprox
Unique values: [nan  2.  1.]
Counts:
rcaprox
1.0    197
2.0    175
Name: count, dtype: int64

Column: rcadist
Unique values: [nan  2.  1.]
Counts:
rcadist
1.0    275
2.0     72
Name: count, dtype: int64