# 1 Dataset Loading

In [45]:
import pandas as pd
import os


clean_heart_disease_data_path = os.path.join(os.getcwd(), '..', 'Data', 'processed', 'clean_heart_disease.data')
df = pd.read_csv(clean_heart_disease_data_path, sep=',')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,40,1,2,140.0,289.0,0.0,0.0,172.0,0.0,0.0,NaN,NaN,NaN,0
1,49,0,3,160.0,180.0,0.0,0.0,156.0,0.0,1.0,2.0,NaN,NaN,1
2,37,1,2,130.0,283.0,0.0,1.0,98.0,0.0,0.0,NaN,NaN,NaN,0
3,48,0,4,138.0,214.0,0.0,0.0,108.0,1.0,1.5,2.0,NaN,NaN,3
4,54,1,3,150.0,NaN,0.0,0.0,122.0,0.0,0.0,NaN,NaN,NaN,0

# 2 Feature Type Identification

In [46]:
target = "num"

numerical_features = [
    "age",
    "trestbps",
    "chol",
    "thalach",
    "oldpeak"
]

binary_features = [
    "sex",
    "fbs",
    "exang"
]

categorical_features = [
    "cp",
    "restecg",
    "slope",
    "thal",
    "ca"
]

In [47]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,40,1,2,140.0,289.0,0.0,0.0,172.0,0.0,0.0,NaN,NaN,NaN,0
1,49,0,3,160.0,180.0,0.0,0.0,156.0,0.0,1.0,2.0,NaN,NaN,1
2,37,1,2,130.0,283.0,0.0,1.0,98.0,0.0,0.0,NaN,NaN,NaN,0
3,48,0,4,138.0,214.0,0.0,0.0,108.0,1.0,1.5,2.0,NaN,NaN,3
4,54,1,3,150.0,NaN,0.0,0.0,122.0,0.0,0.0,NaN,NaN,NaN,0

# 3 Encoding Categorical Features

In [48]:
df_encoded = pd.get_dummies(
    df,
    columns=categorical_features,
    drop_first=True
)

df_encoded.head()

,age,sex,trestbps,chol,fbs,thalach,exang,oldpeak,num,cp_2,...,slope_3.0,thal_2.0,thal_3.0,thal_4.0,thal_5.0,thal_6.0,thal_7.0,ca_1.0,ca_2.0,ca_9.0
0,40,1,140.0,289.0,0.0,172.0,0.0,0.0,0,True,...,False,False,False,False,False,False,False,False,False,False
1,49,0,160.0,180.0,0.0,156.0,0.0,1.0,1,False,...,False,False,False,False,False,False,False,False,False,False
2,37,1,130.0,283.0,0.0,98.0,0.0,0.0,0,True,...,False,False,False,False,False,False,False,False,False,False
3,48,0,138.0,214.0,0.0,108.0,1.0,1.5,3,False,...,False,False,False,False,False,False,False,False,False,False
4,54,1,150.0,NaN,0.0,122.0,0.0,0.0,0,False,...,False,False,False,False,False,False,False,False,False,False

# 4 Feature Scaling

In [49]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df_encoded[numerical_features] = scaler.fit_transform(
    df_encoded[numerical_features]
)

df_encoded.head()

,age,sex,trestbps,chol,fbs,thalach,exang,oldpeak,num,cp_2,...,slope_3.0,thal_2.0,thal_3.0,thal_4.0,thal_5.0,thal_6.0,thal_7.0,ca_1.0,ca_2.0,ca_9.0
0,-1.361573,1,0.384606,0.920861,0.0,1.630430,0.0,-0.762126,0,True,...,False,False,False,False,False,False,False,False,False,False
1,-0.422820,0,1.394242,0.044207,0.0,0.993943,0.0,0.197910,1,False,...,False,False,False,False,False,False,False,False,False,False
2,-1.674491,1,-0.120212,0.872605,0.0,-1.313323,0.0,-0.762126,0,True,...,False,False,False,False,False,False,False,False,False,False
3,-0.527126,0,0.283642,0.317659,0.0,-0.915519,1.0,0.677927,3,False,...,False,False,False,False,False,False,False,False,False,False
4,0.098709,1,0.889424,NaN,0.0,-0.358592,0.0,-0.762126,0,False,...,False,False,False,False,False,False,False,False,False,False

# 5 Feature Validation

In [50]:
df_encoded.isna().sum()

age             0
sex             0
trestbps       59
chol           29
fbs            90
thalach        55
exang          55
oldpeak        62
num             0
cp_2            0
cp_3            0
cp_4            0
restecg_1.0     0
restecg_2.0     0
slope_1.0       0
slope_2.0       0
slope_3.0       0
thal_2.0        0
thal_3.0        0
thal_4.0        0
thal_5.0        0
thal_6.0        0
thal_7.0        0
ca_1.0          0
ca_2.0          0
ca_9.0          0
dtype: int64

In [51]:
df_encoded.dtypes

age            float64
sex              int64
trestbps       float64
chol           float64
fbs            float64
thalach        float64
exang          float64
oldpeak        float64
num              int64
cp_2              bool
cp_3              bool
cp_4              bool
restecg_1.0       bool
restecg_2.0       bool
slope_1.0         bool
slope_2.0         bool
slope_3.0         bool
thal_2.0          bool
thal_3.0          bool
thal_4.0          bool
thal_5.0          bool
thal_6.0          bool
thal_7.0          bool
ca_1.0            bool
ca_2.0            bool
ca_9.0            bool
dtype: object

In [52]:
df_encoded.shape

(615, 26)

In [53]:
df_encoded.describe()

,age,sex,trestbps,chol,fbs,thalach,exang,oldpeak,num
count,6.150000e+02,615.000000,5.560000e+02,5.860000e+02,525.000000,5.600000e+02,560.000000,5.530000e+02,615.000000
mean,-9.242832e-17,0.843902,4.600636e-16,-9.700242e-17,0.177143,3.806479e-16,0.423214,5.139550e-17,1.230894
std,1.000814e+00,0.363243,1.000900e+00,1.000854e+00,0.382154,1.000894e+00,0.494510,1.000905e+00,1.264147
min,-2.613243e+00,0.000000,-6.682845e+00,-1.403478e+00,0.000000,-2.824981e+00,0.000000,-3.258218e+00,0.000000
25%,-6.314321e-01,1.000000,-6.250299e-01,-1.403478e+00,0.000000,-6.768360e-01,0.000000,-7.621258e-01,0.000000
50%,9.870896e-02,1.000000,-1.202120e-01,3.136377e-01,0.000000,-4.034875e-02,0.000000,-7.621258e-01,1.000000
75%,7.245441e-01,1.000000,4.855694e-01,7.117512e-01,0.000000,7.552604e-01,1.000000,6.779274e-01,2.000000
max,2.497744e+00,1.000000,3.413513e+00,3.446268e+00,1.000000,2.346479e+00,1.000000,4.038051e+00,4.000000

# 6 Final Feature Matrix

In [54]:
X = df_encoded.drop("num", axis=1)
y = df_encoded["num"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (615, 25)
Target shape: (615,)

In [55]:
X.head()

,age,sex,trestbps,chol,fbs,thalach,exang,oldpeak,cp_2,cp_3,...,slope_3.0,thal_2.0,thal_3.0,thal_4.0,thal_5.0,thal_6.0,thal_7.0,ca_1.0,ca_2.0,ca_9.0
0,-1.361573,1,0.384606,0.920861,0.0,1.630430,0.0,-0.762126,True,False,...,False,False,False,False,False,False,False,False,False,False
1,-0.422820,0,1.394242,0.044207,0.0,0.993943,0.0,0.197910,False,True,...,False,False,False,False,False,False,False,False,False,False
2,-1.674491,1,-0.120212,0.872605,0.0,-1.313323,0.0,-0.762126,True,False,...,False,False,False,False,False,False,False,False,False,False
3,-0.527126,0,0.283642,0.317659,0.0,-0.915519,1.0,0.677927,False,False,...,False,False,False,False,False,False,False,False,False,False
4,0.098709,1,0.889424,NaN,0.0,-0.358592,0.0,-0.762126,False,True,...,False,False,False,False,False,False,False,False,False,False